version: '3.6'

services:
  dremio:
    build: ./dremio/.
    ports:
      - "0:0:0:0:9047:9047"
      - "0:0:0:0:31010:31010"
      - "0:0:0:0:45678:45678"
    links:
      - mongodb
  mongodb:
    image: "mongo"
    ports:
      - "0:0:0:0:27017:27017"
      - "0:0:0:0:8081:8081"
